<?php include_once(__DIR__ . '/../includes/header.phtml') ?>

<article>
    <img src="/assets/img/me.jpg" alt="Photograph of me" />

    <h1>About me</h1>

    <p>Hey, I'm Sam - a Principal Engineer at <a href="http://www.sky.com">BSkyB</a>, based in Leeds, UK.
       I'm a gamer, liberal thinker and organiser of the <a href="http://leedsphp.org">Leeds PHP</a> user group
       and the <a href="https://twitter.com/LeedsVGC">Leeds Videogame Club</a>.</p>

    <p>Very much into agile, Test Driven Development, Domain Driven Design and Continuous Integration.</p>

    <p>If you'd like to get in touch, you can find me on Twitter <a href="https://twitter.com/samh">@samh</a>
       and <a href="https://github.com/samholman">Github</a>.</p>

    <p>Speak soon. :-)</p>
</article>

<?php include_once(__DIR__ . '/../includes/footer.phtml') ?>

