<!doctype html>
<html lang="en-GB">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title><?php echo isset($this->title) ? $this->title : 'Home' ?> | Sam Holman</title>
    <meta name="description" content="Sam Holman - Senior Software Engineer at BSkyB. Based in Leeds, UK. Agile, TDD, DDD, CI, Gamer, Liberal, organiser of @leedsphp." />

    <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic' rel='stylesheet' type='text/css'>
    <link href="/assets/css/normalize/3.0.1.css" rel="stylesheet" type="text/css" />
    <link href="/assets/css/site.css" rel="stylesheet" type="text/css" />
</head>
<body>
<header>
    <div class="content">
        <div class="me"><a href="/"><img src="/assets/img/yoshi.png" alt="" />Sam Holman</a> - coder, gamer, geek.</div>

        <nav>
            <ul>
                <li><a href="/">Home</a>
                <li><a href="/about">About</a>
            </ul>
        </nav>
    </div>
</header>

<div class="content">
