<!doctype html>
<html lang="en-GB">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="target-densitydpi=device-dpi,width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <title><?php echo isset($this->title) ? $this->title : 'Home' ?> | Sam Holman</title>
    <meta name="description" content="Sam Holman - Senior Software Engineer at BSkyB. Based in Leeds, UK. Agile, TDD, DDD, CI, Gamer, Liberal, organiser of @leedsphp." />

    <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic' rel='stylesheet' type='text/css'>
    <link href="/assets/css/normalize/3.0.1.css" rel="stylesheet" type="text/css" />
    <link href="/assets/css/site.css" rel="stylesheet" type="text/css" />
</head>
<body>
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-51396022-1', 'samholman.com');
    ga('send', 'pageview');
</script>
<header>
    <div class="content">
        <div class="me"><a href="/"><img src="/assets/img/yoshi.png" alt="" />Sam Holman</a><span class="suffix"> - coder, gamer, geek.</span></div>

        <nav>
            <ul>
                <li><a href="/">Home</a>
                <li><a href="/about">About</a>
            </ul>
        </nav>
    </div>
</header>

<div class="content">
