<?php include_once(__DIR__ . '/../../includes/header.phtml') ?>

<?php if ($this->article): ?>
    <article>
        <h1><?php echo $this->article->getTitle() ?></h1>
        <time><?php echo $this->article->getDate()->format('D jS M Y') ?></time>
        <?php echo $this->markdown($this->article->getContent()) ?>

        <div id="disqus_thread"></div>
        <script type="text/javascript">
            /** Config **/
            var disqus_shortname = 'samholman';
            /** End config **/

            (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

        <a href="/" class="readMore">&laquo; Back</a>
    </article>
<?php endif ?>

<?php include_once(__DIR__ . '/../../includes/footer.phtml') ?>
