<?php include_once(__DIR__ . '/../includes/header.phtml') ?>

<article>
    <img src="/assets/img/me.jpg" alt="Photograph of me" />

    <h1>About me</h1>

    <p>Hey, I'm Sam - a Senior Software Engineer at BSkyB.</p>
    <p>Based in Leeds, UK. I'm very much into agile, Test Driven Development, Domain Driven Design and Continuous Integration.</p>
    <p>I'm a gamer, liberal thinker and organiser of the <a href="http://leedsphp.org">Leeds PHP</a> user group.</p>

    <p>You can find me on Twitter <a href="https://twitter.com/samh">@samh</a> and <a href="https://github.com/samholman">Github</a>.</p>

    <p>Speak soon. :-)</p>
</article>

<?php include_once(__DIR__ . '/../includes/footer.phtml') ?>